<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class_performance']=array (
  'id' => '178',
  'name' => 'class_performance',
  'description' => '学员课堂表现',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    904 => 
    array (
      'id' => '904',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '178',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    905 => 
    array (
      'id' => '905',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '178',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    972 => 
    array (
      'id' => '972',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '178',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    906 => 
    array (
      'id' => '906',
      'name' => 'video_1',
      'description' => '视频1',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【存储腾讯云点播信息】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    907 => 
    array (
      'id' => '907',
      'name' => 'text_1',
      'description' => '文案1',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    908 => 
    array (
      'id' => '908',
      'name' => 'video_2',
      'description' => '视频2',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【存储腾讯云点播信息】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    909 => 
    array (
      'id' => '909',
      'name' => 'text_2',
      'description' => '文案2',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    910 => 
    array (
      'id' => '910',
      'name' => 'video_3',
      'description' => '视频3',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【存储腾讯云点播信息】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    911 => 
    array (
      'id' => '911',
      'name' => 'text_3',
      'description' => '文案3',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    912 => 
    array (
      'id' => '912',
      'name' => 'video_4',
      'description' => '视频4',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【存储腾讯云点播信息】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    913 => 
    array (
      'id' => '913',
      'name' => 'text_4',
      'description' => '文案4',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    914 => 
    array (
      'id' => '914',
      'name' => 'video_5',
      'description' => '视频5',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【存储腾讯云点播信息】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    915 => 
    array (
      'id' => '915',
      'name' => 'text_5',
      'description' => '文案5',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1051 => 
    array (
      'id' => '1051',
      'name' => 'video_6',
      'description' => '视频6',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1052 => 
    array (
      'id' => '1052',
      'name' => 'text_6',
      'description' => '文案6',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1053 => 
    array (
      'id' => '1053',
      'name' => 'video_7',
      'description' => '视频7',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    1054 => 
    array (
      'id' => '1054',
      'name' => 'text_7',
      'description' => '文案7',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    1055 => 
    array (
      'id' => '1055',
      'name' => 'video_8',
      'description' => '视频8',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1056 => 
    array (
      'id' => '1056',
      'name' => 'text_8',
      'description' => '文案8',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1057 => 
    array (
      'id' => '1057',
      'name' => 'video_9',
      'description' => '视频9',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1058 => 
    array (
      'id' => '1058',
      'name' => 'text_9',
      'description' => '文案9',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1059 => 
    array (
      'id' => '1059',
      'name' => 'video_10',
      'description' => '视频10',
      'model' => '178',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '17',
      'editable' => '1',
    ),
    1060 => 
    array (
      'id' => '1060',
      'name' => 'text_10',
      'description' => '文案10',
      'model' => '178',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '17',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '904',
    1 => '905',
    2 => '972',
    3 => '906',
    4 => '907',
    5 => '908',
    6 => '909',
    7 => '910',
    8 => '911',
    9 => '912',
    10 => '913',
    11 => '914',
    12 => '915',
    13 => '1051',
    14 => '1052',
    15 => '1053',
    16 => '1054',
    17 => '1055',
    18 => '1056',
    19 => '1057',
    20 => '1058',
    21 => '1059',
    22 => '1060',
  ),
  'searchable' => 
  array (
    0 => '904',
    1 => '905',
    2 => '972',
    3 => '906',
    4 => '907',
    5 => '908',
    6 => '909',
    7 => '910',
    8 => '911',
    9 => '912',
    10 => '913',
    11 => '914',
    12 => '915',
    13 => '1051',
    14 => '1052',
    15 => '1053',
    16 => '1054',
    17 => '1055',
    18 => '1056',
    19 => '1057',
    20 => '1058',
    21 => '1059',
    22 => '1060',
  ),
);