<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class']=array (
  'id' => '157',
  'name' => 'class',
  'description' => '班级列表',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    747 => 
    array (
      'id' => '747',
      'name' => 'class_id',
      'description' => '班级id(业务)',
      'model' => '157',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    1000 => 
    array (
      'id' => '1000',
      'name' => 'class_sn',
      'description' => '班级编号(业务)',
      'model' => '157',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    720 => 
    array (
      'id' => '720',
      'name' => 'class_name',
      'description' => '班级名称(业务)',
      'model' => '157',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '200',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    750 => 
    array (
      'id' => '750',
      'name' => 'class_rename',
      'description' => '班级名称',
      'model' => '157',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '400',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    721 => 
    array (
      'id' => '721',
      'name' => 'start_time',
      'description' => '开始时间',
      'model' => '157',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '2',
      'editable' => '1',
    ),
    722 => 
    array (
      'id' => '722',
      'name' => 'end_time',
      'description' => '结束时间',
      'model' => '157',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
    748 => 
    array (
      'id' => '748',
      'name' => 'class_time',
      'description' => '上课时间段',
      'model' => '157',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
    723 => 
    array (
      'id' => '723',
      'name' => 'class_number',
      'description' => '班级人数',
      'model' => '157',
      'type' => 'int',
      'length' => '10',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '4',
      'editable' => '1',
    ),
    730 => 
    array (
      'id' => '730',
      'name' => 'order_number',
      'description' => '可预约名额',
      'model' => '157',
      'type' => 'int',
      'length' => '10',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
    724 => 
    array (
      'id' => '724',
      'name' => 'price',
      'description' => '原价',
      'model' => '157',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
    806 => 
    array (
      'id' => '806',
      'name' => 'begin_date',
      'description' => '开课时间',
      'model' => '157',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    725 => 
    array (
      'id' => '725',
      'name' => 'close_date',
      'description' => '结课时间',
      'model' => '157',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    731 => 
    array (
      'id' => '731',
      'name' => 'upper_shelf',
      'description' => '是否上架',
      'model' => '157',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        0 => '下架',
        1 => '上架',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '9',
      'editable' => '1',
    ),
    751 => 
    array (
      'id' => '751',
      'name' => 'sign_up_type',
      'description' => '报名方式',
      'model' => '157',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '线上缴费',
        '' => '预约到店',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '9',
      'editable' => '1',
    ),
    729 => 
    array (
      'id' => '729',
      'name' => 'belong_course',
      'description' => '所属课程产品',
      'model' => '157',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    928 => 
    array (
      'id' => '928',
      'name' => 'belong_course_rename',
      'description' => '所属课程备注',
      'model' => '157',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '10',
      'editable' => '1',
    ),
    773 => 
    array (
      'id' => '773',
      'name' => 'belong_district',
      'description' => '所属校区id',
      'model' => '157',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    801 => 
    array (
      'id' => '801',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '157',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    939 => 
    array (
      'id' => '939',
      'name' => 'headmaster_name',
      'description' => '班主任名称',
      'model' => '157',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    809 => 
    array (
      'id' => '809',
      'name' => 'teacher_id',
      'description' => '任课老师id',
      'model' => '157',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '13',
      'editable' => '1',
    ),
    831 => 
    array (
      'id' => '831',
      'name' => 'bind_course_name',
      'description' => '绑定课程产品名称[课次]',
      'model' => '157',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    958 => 
    array (
      'id' => '958',
      'name' => 'class_sort',
      'description' => '排序',
      'model' => '157',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '15',
      'editable' => '1',
    ),
    961 => 
    array (
      'id' => '961',
      'name' => 'status',
      'description' => '状态',
      'model' => '157',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        2 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1074 => 
    array (
      'id' => '1074',
      'name' => 'sys_status',
      'description' => '状态[业务]',
      'model' => '157',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '新班',
        2 => '已开班',
        3 => '已结班',
        4 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    970 => 
    array (
      'id' => '970',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '157',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '17',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '747',
    1 => '1000',
    2 => '720',
    3 => '750',
    4 => '806',
    5 => '725',
    6 => '729',
    7 => '773',
    8 => '801',
    9 => '939',
    10 => '831',
    11 => '961',
    12 => '1074',
    13 => '970',
  ),
  'searchable' => 
  array (
    0 => '747',
    1 => '1000',
    2 => '720',
    3 => '750',
    4 => '721',
    5 => '722',
    6 => '748',
    7 => '723',
    8 => '730',
    9 => '724',
    10 => '806',
    11 => '725',
    12 => '731',
    13 => '751',
    14 => '729',
    15 => '928',
    16 => '773',
    17 => '801',
    18 => '939',
    19 => '809',
    20 => '831',
    21 => '958',
    22 => '961',
    23 => '1074',
    24 => '970',
  ),
);