<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class_time']=array (
  'id' => '173',
  'name' => 'class_time',
  'description' => '班级课次',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    832 => 
    array (
      'id' => '832',
      'name' => 'course_product',
      'description' => '课程产品',
      'model' => '173',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    833 => 
    array (
      'id' => '833',
      'name' => 'course_structure',
      'description' => '课程单元',
      'model' => '173',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    854 => 
    array (
      'id' => '854',
      'name' => 'class_time',
      'description' => '上课时间',
      'model' => '173',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    836 => 
    array (
      'id' => '836',
      'name' => 'course_theme',
      'description' => '课程主题',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    837 => 
    array (
      'id' => '837',
      'name' => 'teaching_objectives',
      'description' => '教学目标',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    838 => 
    array (
      'id' => '838',
      'name' => 'courses_content',
      'description' => '教学内容',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    839 => 
    array (
      'id' => '839',
      'name' => 'homework',
      'description' => '课后作业',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    932 => 
    array (
      'id' => '932',
      'name' => 'class_bright',
      'description' => '课后亮点',
      'model' => '173',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    840 => 
    array (
      'id' => '840',
      'name' => 'book_name',
      'description' => '绘本名称',
      'model' => '173',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    841 => 
    array (
      'id' => '841',
      'name' => 'book_id',
      'description' => '绘本id',
      'model' => '173',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    955 => 
    array (
      'id' => '955',
      'name' => 'audio',
      'description' => '教材音频',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    957 => 
    array (
      'id' => '957',
      'name' => 'baidu_pan',
      'description' => '百度网盘二维码',
      'model' => '173',
      'type' => 'input',
      'length' => '1000',
      'values' => '',
      'width' => '500',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1022 => 
    array (
      'id' => '1022',
      'name' => 'gpa',
      'description' => 'gpa',
      'model' => '173',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '400',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1030 => 
    array (
      'id' => '1030',
      'name' => 'video_cover',
      'description' => '视频封面',
      'model' => '173',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1031 => 
    array (
      'id' => '1031',
      'name' => 'video',
      'description' => '视频',
      'model' => '173',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    842 => 
    array (
      'id' => '842',
      'name' => 'belong_class_id',
      'description' => '所属班级id',
      'model' => '173',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    920 => 
    array (
      'id' => '920',
      'name' => 'belong_curriculum_id',
      'description' => '所属课程id',
      'model' => '173',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    869 => 
    array (
      'id' => '869',
      'name' => 'status',
      'description' => '状态',
      'model' => '173',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '已发布',
        0 => '待编辑',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    976 => 
    array (
      'id' => '976',
      'name' => 'h5_template',
      'description' => 'H5模板',
      'model' => '173',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '默认',
        1 => '秋季模板',
        2 => '万圣节',
        3 => '感恩节',
        4 => '圣诞节',
        5 => '寒假',
        6 => '春季T4',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    978 => 
    array (
      'id' => '978',
      'name' => 'release_time',
      'description' => '发布时间',
      'model' => '173',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '832',
    1 => '833',
    2 => '854',
    3 => '836',
    4 => '837',
    5 => '838',
    6 => '839',
    7 => '932',
    8 => '840',
    9 => '841',
    10 => '955',
    11 => '957',
    12 => '1022',
    13 => '1030',
    14 => '1031',
    15 => '842',
    16 => '920',
    17 => '869',
    18 => '976',
    19 => '978',
  ),
  'searchable' => 
  array (
    0 => '832',
    1 => '833',
    2 => '854',
    3 => '836',
    4 => '837',
    5 => '838',
    6 => '839',
    7 => '932',
    8 => '840',
    9 => '841',
    10 => '955',
    11 => '957',
    12 => '1022',
    13 => '1030',
    14 => '1031',
    15 => '842',
    16 => '920',
    17 => '869',
    18 => '976',
    19 => '978',
  ),
);