<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class_times']=array (
  'id' => '172',
  'name' => 'class_times',
  'description' => '班级课次库',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    821 => 
    array (
      'id' => '821',
      'name' => 'course_product',
      'description' => '课程产品名称',
      'model' => '172',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    822 => 
    array (
      'id' => '822',
      'name' => 'course_structure',
      'description' => '课程单元',
      'model' => '172',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    825 => 
    array (
      'id' => '825',
      'name' => 'course_theme',
      'description' => '课程主题',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    826 => 
    array (
      'id' => '826',
      'name' => 'teaching_objectives',
      'description' => '教学目标',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    827 => 
    array (
      'id' => '827',
      'name' => 'courses_content',
      'description' => '教学内容',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    828 => 
    array (
      'id' => '828',
      'name' => 'homework',
      'description' => '课后作业',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    929 => 
    array (
      'id' => '929',
      'name' => 'class_bright',
      'description' => '课后亮点',
      'model' => '172',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    882 => 
    array (
      'id' => '882',
      'name' => 'book_id',
      'description' => '绘本id',
      'model' => '172',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    829 => 
    array (
      'id' => '829',
      'name' => 'book_name',
      'description' => '绘本名称',
      'model' => '172',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    954 => 
    array (
      'id' => '954',
      'name' => 'audio',
      'description' => '教材音频',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    956 => 
    array (
      'id' => '956',
      'name' => 'baidu_pan',
      'description' => '百度网盘二维码',
      'model' => '172',
      'type' => 'input',
      'length' => '1000',
      'values' => '',
      'width' => '500',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1021 => 
    array (
      'id' => '1021',
      'name' => 'gpa',
      'description' => 'gpa',
      'model' => '172',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '400',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1028 => 
    array (
      'id' => '1028',
      'name' => 'video_cover',
      'description' => '视频封面',
      'model' => '172',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1029 => 
    array (
      'id' => '1029',
      'name' => 'video',
      'description' => '视频',
      'model' => '172',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    933 => 
    array (
      'id' => '933',
      'name' => 'school_district_id',
      'description' => '校区id',
      'model' => '172',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    977 => 
    array (
      'id' => '977',
      'name' => 'status',
      'description' => '状态',
      'model' => '172',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '显示',
        2 => '隐藏',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '821',
    1 => '822',
    2 => '825',
    3 => '826',
    4 => '827',
    5 => '828',
    6 => '929',
    7 => '882',
    8 => '829',
    9 => '954',
    10 => '956',
    11 => '1021',
    12 => '1028',
    13 => '1029',
    14 => '933',
    15 => '977',
  ),
  'searchable' => 
  array (
    0 => '821',
    1 => '822',
    2 => '825',
    3 => '826',
    4 => '827',
    5 => '828',
    6 => '929',
    7 => '882',
    8 => '829',
    9 => '954',
    10 => '956',
    11 => '1021',
    12 => '1028',
    13 => '1029',
    14 => '933',
    15 => '977',
  ),
);