<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class_preview']=array (
  'id' => '191',
  'name' => 'class_preview',
  'description' => '课前预习',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    1094 => 
    array (
      'id' => '1094',
      'name' => 'remind_type',
      'description' => '提醒类型',
      'model' => '191',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '课前',
        1 => '课后',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    1088 => 
    array (
      'id' => '1088',
      'name' => 'lead_time',
      'description' => '提前时间',
      'model' => '191',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1097 => 
    array (
      'id' => '1097',
      'name' => 'specific_time',
      'description' => '具体时间',
      'model' => '191',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1089 => 
    array (
      'id' => '1089',
      'name' => 'switch',
      'description' => '状态',
      'model' => '191',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '开启',
        2 => '关闭',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1090 => 
    array (
      'id' => '1090',
      'name' => 'image',
      'description' => '图片',
      'model' => '191',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1091 => 
    array (
      'id' => '1091',
      'name' => 'belong_class_id',
      'description' => '所属班级id',
      'model' => '191',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    1092 => 
    array (
      'id' => '1092',
      'name' => 'belong_curriculum_id',
      'description' => '所属课程id',
      'model' => '191',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1093 => 
    array (
      'id' => '1093',
      'name' => 'template_message',
      'description' => '模板消息',
      'model' => '191',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '未发送',
        1 => '已发送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1094',
    1 => '1088',
    2 => '1097',
    3 => '1089',
    4 => '1090',
    5 => '1091',
    6 => '1092',
    7 => '1093',
  ),
  'searchable' => 
  array (
    0 => '1094',
    1 => '1088',
    2 => '1097',
    3 => '1089',
    4 => '1090',
    5 => '1091',
    6 => '1092',
    7 => '1093',
  ),
);