<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['class_remind']=array (
  'id' => '190',
  'name' => 'class_remind',
  'description' => '课前提醒',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    1078 => 
    array (
      'id' => '1078',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '190',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1079 => 
    array (
      'id' => '1079',
      'name' => 'class_id',
      'description' => '班级id',
      'model' => '190',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1080 => 
    array (
      'id' => '1080',
      'name' => 'curriculum_id',
      'description' => '课程id',
      'model' => '190',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1081 => 
    array (
      'id' => '1081',
      'name' => 'switch',
      'description' => '开关',
      'model' => '190',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        0 => '关',
        1 => '开',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    1082 => 
    array (
      'id' => '1082',
      'name' => 'hours',
      'description' => '提前时间',
      'model' => '190',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1083 => 
    array (
      'id' => '1083',
      'name' => 'location',
      'description' => '上课地点',
      'model' => '190',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    1084 => 
    array (
      'id' => '1084',
      'name' => 'remarks',
      'description' => '备注',
      'model' => '190',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1078',
    1 => '1079',
    2 => '1080',
    3 => '1081',
    4 => '1082',
    5 => '1083',
    6 => '1084',
  ),
  'searchable' => 
  array (
    0 => '1078',
    1 => '1079',
    2 => '1080',
    3 => '1081',
    4 => '1082',
    5 => '1083',
    6 => '1084',
  ),
);