<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['course']=array (
  'id' => '156',
  'name' => 'course',
  'description' => '课程产品列表',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    746 => 
    array (
      'id' => '746',
      'name' => 'course_id',
      'description' => '课程产品id(业务系统)',
      'model' => '156',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    719 => 
    array (
      'id' => '719',
      'name' => 'course_name',
      'description' => '课程产品名称(业务系统)',
      'model' => '156',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    749 => 
    array (
      'id' => '749',
      'name' => 'course_rename',
      'description' => '课程产品名称',
      'model' => '156',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    803 => 
    array (
      'id' => '803',
      'name' => 'class_hour',
      'description' => '课时',
      'model' => '156',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    805 => 
    array (
      'id' => '805',
      'name' => 'semester',
      'description' => '学期',
      'model' => '156',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    728 => 
    array (
      'id' => '728',
      'name' => 'belong_school',
      'description' => '所属学校id',
      'model' => '156',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    969 => 
    array (
      'id' => '969',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '156',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '746',
    1 => '719',
    2 => '749',
    3 => '803',
    4 => '805',
    5 => '728',
    6 => '969',
  ),
  'searchable' => 
  array (
    0 => '746',
    1 => '719',
    2 => '749',
    3 => '803',
    4 => '805',
    5 => '728',
    6 => '969',
  ),
);