<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['curriculum']=array (
  'id' => '180',
  'name' => 'curriculum',
  'description' => '课程列表',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    921 => 
    array (
      'id' => '921',
      'name' => 'curriculum_id',
      'description' => '课程id[业务]',
      'model' => '180',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    922 => 
    array (
      'id' => '922',
      'name' => 'curriculum_name',
      'description' => '课程名称[业务]',
      'model' => '180',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    923 => 
    array (
      'id' => '923',
      'name' => 'curriculum_rename',
      'description' => '课程备注名称',
      'model' => '180',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    936 => 
    array (
      'id' => '936',
      'name' => 'curriculum_count',
      'description' => '课时',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
    924 => 
    array (
      'id' => '924',
      'name' => 'belong_class_id',
      'description' => '所属班级id',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    942 => 
    array (
      'id' => '942',
      'name' => 'belong_class_rename',
      'description' => '所属班级备注名称',
      'model' => '180',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    925 => 
    array (
      'id' => '925',
      'name' => 'belong_course_id',
      'description' => '所属课程产品id',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    959 => 
    array (
      'id' => '959',
      'name' => 'bind_course_name',
      'description' => '绑定课次产品',
      'model' => '180',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1008 => 
    array (
      'id' => '1008',
      'name' => 'bind_gpa',
      'description' => '绑定gpa',
      'model' => '180',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    926 => 
    array (
      'id' => '926',
      'name' => 'teacher_id',
      'description' => '任课老师id',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    937 => 
    array (
      'id' => '937',
      'name' => 'belong_district',
      'description' => '校区id',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    927 => 
    array (
      'id' => '927',
      'name' => 'belong_school',
      'description' => '所属学校id',
      'model' => '180',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    975 => 
    array (
      'id' => '975',
      'name' => 'status',
      'description' => '状态',
      'model' => '180',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        2 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    938 => 
    array (
      'id' => '938',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '180',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '921',
    1 => '922',
    2 => '923',
    3 => '924',
    4 => '942',
    5 => '925',
    6 => '959',
    7 => '1008',
    8 => '926',
    9 => '937',
    10 => '927',
    11 => '975',
    12 => '938',
  ),
  'searchable' => 
  array (
    0 => '921',
    1 => '922',
    2 => '923',
    3 => '936',
    4 => '924',
    5 => '942',
    6 => '925',
    7 => '959',
    8 => '1008',
    9 => '926',
    10 => '937',
    11 => '927',
    12 => '975',
    13 => '938',
  ),
);