<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['edit_lesson_record']=array (
  'id' => '182',
  'name' => 'edit_lesson_record',
  'description' => '编辑课次记录',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    965 => 
    array (
      'id' => '965',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '182',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    966 => 
    array (
      'id' => '966',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '182',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    967 => 
    array (
      'id' => '967',
      'name' => 'curriculum_id',
      'description' => '课程id',
      'model' => '182',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    968 => 
    array (
      'id' => '968',
      'name' => 'class_id',
      'description' => '班级id',
      'model' => '182',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    1064 => 
    array (
      'id' => '1064',
      'name' => 'type',
      'description' => '类型',
      'model' => '182',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '课次',
        1 => '报告',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '965',
    1 => '966',
    2 => '967',
    3 => '968',
    4 => '1064',
  ),
  'searchable' => 
  array (
    0 => '965',
    1 => '966',
    2 => '967',
    3 => '968',
    4 => '1064',
  ),
);