<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['enclosure']=array (
  'id' => '186',
  'name' => 'enclosure',
  'description' => '学员附件',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    1017 => 
    array (
      'id' => '1017',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '186',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1018 => 
    array (
      'id' => '1018',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '186',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1019 => 
    array (
      'id' => '1019',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '186',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1020 => 
    array (
      'id' => '1020',
      'name' => 'enclosure_json',
      'description' => '附件json',
      'model' => '186',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1017',
    1 => '1018',
    2 => '1019',
    3 => '1020',
  ),
  'searchable' => 
  array (
    0 => '1017',
    1 => '1018',
    2 => '1019',
    3 => '1020',
  ),
);