<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['headmaster']=array (
  'id' => '154',
  'name' => 'headmaster',
  'description' => '后台账户信息',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '17',
  'model_sort' => '1',
  'fields' => 
  array (
    902 => 
    array (
      'id' => '902',
      'name' => 'headmaster_id',
      'description' => '用户id【业务】',
      'model' => '154',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    774 => 
    array (
      'id' => '774',
      'name' => 'account',
      'description' => '账号',
      'model' => '154',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    708 => 
    array (
      'id' => '708',
      'name' => 'nickName',
      'description' => '昵称',
      'model' => '154',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    715 => 
    array (
      'id' => '715',
      'name' => 'user_pw',
      'description' => '密码',
      'model' => '154',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    934 => 
    array (
      'id' => '934',
      'name' => 'telephone',
      'description' => '手机号',
      'model' => '154',
      'type' => 'input',
      'length' => '11',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    716 => 
    array (
      'id' => '716',
      'name' => 'user_type',
      'description' => '用户类型',
      'model' => '154',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '班主任',
        2 => '任课老师',
        3 => '校区管理员',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    800 => 
    array (
      'id' => '800',
      'name' => 'head_portrait',
      'description' => '头像',
      'model' => '154',
      'type' => 'file',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    717 => 
    array (
      'id' => '717',
      'name' => 'school',
      'description' => '所属校区id',
      'model' => '154',
      'type' => 'input',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【填写校区列表ID字段】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    935 => 
    array (
      'id' => '935',
      'name' => 'school_id',
      'description' => '所属学校id',
      'model' => '154',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    918 => 
    array (
      'id' => '918',
      'name' => 'curriculum_class',
      'description' => '任课班级',
      'model' => '154',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    1095 => 
    array (
      'id' => '1095',
      'name' => 'incumbency',
      'description' => '在职状态',
      'model' => '154',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '在职',
        2 => '离职',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    1096 => 
    array (
      'id' => '1096',
      'name' => 'leave_date',
      'description' => '离职日期',
      'model' => '154',
      'type' => 'datetime',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    903 => 
    array (
      'id' => '903',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '154',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '902',
    1 => '774',
    2 => '708',
    3 => '715',
    4 => '934',
    5 => '716',
    6 => '800',
    7 => '717',
    8 => '935',
    9 => '918',
    10 => '1095',
    11 => '1096',
    12 => '903',
  ),
  'searchable' => 
  array (
    0 => '902',
    1 => '774',
    2 => '708',
    3 => '715',
    4 => '934',
    5 => '716',
    6 => '800',
    7 => '717',
    8 => '935',
    9 => '918',
    10 => '1095',
    11 => '1096',
    12 => '903',
  ),
);