<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['lesson_access_record']=array (
  'id' => '183',
  'name' => 'lesson_access_record',
  'description' => '课次访问记录',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    979 => 
    array (
      'id' => '979',
      'name' => 'wx_user_id',
      'description' => '微信用户id',
      'model' => '183',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    980 => 
    array (
      'id' => '980',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '183',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    981 => 
    array (
      'id' => '981',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '183',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    982 => 
    array (
      'id' => '982',
      'name' => 'ip_address',
      'description' => 'IP地址',
      'model' => '183',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    983 => 
    array (
      'id' => '983',
      'name' => 'ip_location',
      'description' => 'IP定位',
      'model' => '183',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1014 => 
    array (
      'id' => '1014',
      'name' => 'record_type',
      'description' => '类型',
      'model' => '183',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '分享课次',
        1 => '非分享课次',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '979',
    1 => '980',
    2 => '981',
    3 => '982',
    4 => '983',
    5 => '1014',
  ),
  'searchable' => 
  array (
    0 => '979',
    1 => '980',
    2 => '981',
    3 => '982',
    4 => '983',
    5 => '1014',
  ),
);