<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['new_year_report']=array (
  'id' => '188',
  'name' => 'new_year_report',
  'description' => '新年成绩单',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '26',
  'model_sort' => '0',
  'fields' => 
  array (
    1032 => 
    array (
      'id' => '1032',
      'name' => 'openid',
      'description' => 'openid',
      'model' => '188',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '240',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1033 => 
    array (
      'id' => '1033',
      'name' => 'nickName',
      'description' => '昵称',
      'model' => '188',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1034 => 
    array (
      'id' => '1034',
      'name' => 'school_district',
      'description' => '校区',
      'model' => '188',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        'cd' => '成都',
        'nj' => '南京',
        'sh' => '上海',
        'sz' => '深圳',
        'xian' => '西安',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1035 => 
    array (
      'id' => '1035',
      'name' => 'fit_school',
      'description' => '适合学校',
      'model' => '188',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1032',
    1 => '1033',
    2 => '1034',
    3 => '1035',
  ),
  'searchable' => 
  array (
    0 => '1032',
    1 => '1033',
    2 => '1034',
    3 => '1035',
  ),
);