<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['notice']=array (
  'id' => '165',
  'name' => 'notice',
  'description' => '通知消息',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '23',
  'model_sort' => '0',
  'fields' => 
  array (
    782 => 
    array (
      'id' => '782',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '165',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    783 => 
    array (
      'id' => '783',
      'name' => 'school_district_id',
      'description' => '校区id',
      'model' => '165',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    784 => 
    array (
      'id' => '784',
      'name' => 'class_id',
      'description' => '班级id',
      'model' => '165',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【多个班级用英文逗号隔开，如：1,2,3】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    785 => 
    array (
      'id' => '785',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '165',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '【多个学生用英文逗号隔开，如：1,2,3】',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    787 => 
    array (
      'id' => '787',
      'name' => 'notice_type',
      'description' => '通知类型',
      'model' => '165',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '校区',
        2 => '班级',
        3 => '个人',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    892 => 
    array (
      'id' => '892',
      'name' => 'is_reply',
      'description' => '是否回复',
      'model' => '165',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '否',
        0 => '否',
        1 => '是',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    799 => 
    array (
      'id' => '799',
      'name' => 'notice_title',
      'description' => '通知标题',
      'model' => '165',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    786 => 
    array (
      'id' => '786',
      'name' => 'notice_content',
      'description' => '通知内容',
      'model' => '165',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    919 => 
    array (
      'id' => '919',
      'name' => 'send_status',
      'description' => '发送状态',
      'model' => '165',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '待发送',
        0 => '待发送',
        1 => '已发送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    973 => 
    array (
      'id' => '973',
      'name' => 'is_del',
      'description' => '是否删除',
      'model' => '165',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        2 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '782',
    1 => '783',
    2 => '784',
    3 => '785',
    4 => '787',
    5 => '892',
    6 => '799',
    7 => '786',
    8 => '919',
    9 => '973',
  ),
  'searchable' => 
  array (
    0 => '782',
    1 => '783',
    2 => '784',
    3 => '785',
    4 => '787',
    5 => '892',
    6 => '799',
    7 => '786',
    8 => '919',
    9 => '973',
  ),
);