<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['parent_comments']=array (
  'id' => '176',
  'name' => 'parent_comments',
  'description' => '家长点评',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    871 => 
    array (
      'id' => '871',
      'name' => 'wx_user_id',
      'description' => '微信用户id',
      'model' => '176',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    872 => 
    array (
      'id' => '872',
      'name' => 'student_id',
      'description' => '学员id',
      'model' => '176',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    873 => 
    array (
      'id' => '873',
      'name' => 'lesson_id',
      'description' => '课次/报告id',
      'model' => '176',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    874 => 
    array (
      'id' => '874',
      'name' => 'course_content',
      'description' => '课程内容',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    875 => 
    array (
      'id' => '875',
      'name' => 'operation_volume',
      'description' => '作业量',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    876 => 
    array (
      'id' => '876',
      'name' => 'homework_correction',
      'description' => '作业批改',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    877 => 
    array (
      'id' => '877',
      'name' => 'foreign_teachers',
      'description' => '外教满意度',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    878 => 
    array (
      'id' => '878',
      'name' => 'campus_environment',
      'description' => '校区环境满意度',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    879 => 
    array (
      'id' => '879',
      'name' => 'headmaster',
      'description' => '助教/班主任满意度',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    880 => 
    array (
      'id' => '880',
      'name' => 'feedback',
      'description' => '意见反馈',
      'model' => '176',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '540',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1001 => 
    array (
      'id' => '1001',
      'name' => 'feedback_type',
      'description' => '反馈类型',
      'model' => '176',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '课次反馈',
        1 => '报告反馈',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    1075 => 
    array (
      'id' => '1075',
      'name' => 'keywords',
      'description' => '关键字',
      'model' => '176',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1076 => 
    array (
      'id' => '1076',
      'name' => 'positive',
      'description' => '正向情感',
      'model' => '176',
      'type' => 'textarea',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1077 => 
    array (
      'id' => '1077',
      'name' => 'negative',
      'description' => '负向情感',
      'model' => '176',
      'type' => 'textarea',
      'length' => '20',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '871',
    1 => '872',
    2 => '873',
    3 => '874',
    4 => '875',
    5 => '876',
    6 => '877',
    7 => '878',
    8 => '879',
    9 => '880',
    10 => '1001',
    11 => '1075',
    12 => '1076',
    13 => '1077',
  ),
  'searchable' => 
  array (
    0 => '871',
    1 => '872',
    2 => '873',
    3 => '874',
    4 => '875',
    5 => '876',
    6 => '877',
    7 => '878',
    8 => '879',
    9 => '880',
    10 => '1001',
    11 => '1075',
    12 => '1076',
    13 => '1077',
  ),
);