<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['qrcode_statistics']=array (
  'id' => '187',
  'name' => 'qrcode_statistics',
  'description' => '小助手统计',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    1024 => 
    array (
      'id' => '1024',
      'name' => 'wx_user_id',
      'description' => '微信用户id',
      'model' => '187',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1025 => 
    array (
      'id' => '1025',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '187',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1026 => 
    array (
      'id' => '1026',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '187',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1027 => 
    array (
      'id' => '1027',
      'name' => 'h5_template',
      'description' => 'h5模板',
      'model' => '187',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '默认',
        1 => '秋季模板',
        2 => '万圣节',
        3 => '感恩节',
        4 => '圣诞节',
        5 => '寒假',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1024',
    1 => '1025',
    2 => '1026',
    3 => '1027',
  ),
  'searchable' => 
  array (
    0 => '1024',
    1 => '1025',
    2 => '1026',
    3 => '1027',
  ),
);