<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['report_comment']=array (
  'id' => '185',
  'name' => 'report_comment',
  'description' => '学员报告评价',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '26',
  'model_sort' => '0',
  'fields' => 
  array (
    991 => 
    array (
      'id' => '991',
      'name' => 'report_id',
      'description' => '报告id',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    992 => 
    array (
      'id' => '992',
      'name' => 'student_id',
      'description' => '学员id',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    993 => 
    array (
      'id' => '993',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    994 => 
    array (
      'id' => '994',
      'name' => 'completion_rate',
      'description' => '完成率/作业完成率',
      'model' => '185',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    995 => 
    array (
      'id' => '995',
      'name' => 'excellent_rate',
      'description' => '评优率',
      'model' => '185',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    996 => 
    array (
      'id' => '996',
      'name' => 'biggest_progress',
      'description' => '进步最大/最佳项',
      'model' => '185',
      'type' => 'textarea',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    997 => 
    array (
      'id' => '997',
      'name' => 'foreign_comment',
      'description' => '外教点评',
      'model' => '185',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    998 => 
    array (
      'id' => '998',
      'name' => 'learn_suggest',
      'description' => '学习建议',
      'model' => '185',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1061 => 
    array (
      'id' => '1061',
      'name' => 'compositions_num',
      'description' => '写作篇数',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1062 => 
    array (
      'id' => '1062',
      'name' => 'weak_item',
      'description' => '薄弱项',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1063 => 
    array (
      'id' => '1063',
      'name' => 'exam_score',
      'description' => '统考分数',
      'model' => '185',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    999 => 
    array (
      'id' => '999',
      'name' => 'send_status',
      'description' => '发送状态',
      'model' => '185',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '待发送',
        1 => '已发送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '991',
    1 => '992',
    2 => '993',
    3 => '994',
    4 => '995',
    5 => '996',
    6 => '997',
    7 => '998',
    8 => '1061',
    9 => '1062',
    10 => '1063',
    11 => '999',
  ),
  'searchable' => 
  array (
    0 => '991',
    1 => '992',
    2 => '993',
    3 => '994',
    4 => '995',
    5 => '996',
    6 => '997',
    7 => '998',
    8 => '1061',
    9 => '1062',
    10 => '1063',
    11 => '999',
  ),
);