<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['s_1']=array (
  'id' => '193',
  'name' => 's_1',
  'description' => '完整示例',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '17',
  'model_sort' => '30',
  'fields' => 
  array (
    1126 => 
    array (
      'id' => '1126',
      'name' => 'user_name',
      'description' => 'user_name',
      'model' => '193',
      'type' => 'int',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1127 => 
    array (
      'id' => '1127',
      'name' => 'user_age',
      'description' => 'user_age',
      'model' => '193',
      'type' => 'int',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1128 => 
    array (
      'id' => '1128',
      'name' => 'user_rename',
      'description' => 'user_rename',
      'model' => '193',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '200',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1129 => 
    array (
      'id' => '1129',
      'name' => 'float_1',
      'description' => 'float_1',
      'model' => '193',
      'type' => 'float',
      'length' => '10',
      'values' => '',
      'width' => '200',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1130 => 
    array (
      'id' => '1130',
      'name' => 'json_1',
      'description' => 'json_1',
      'model' => '193',
      'type' => 'textarea_json',
      'length' => '100',
      'values' => '',
      'width' => '500',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1131 => 
    array (
      'id' => '1131',
      'name' => 'select_int',
      'description' => 'select_int',
      'model' => '193',
      'type' => 'select_int',
      'length' => '10',
      'values' => 
      array (
        1 => '选项1',
        2 => '选项2',
      ),
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1132 => 
    array (
      'id' => '1132',
      'name' => 'select_varchar',
      'description' => 'select_varchar',
      'model' => '193',
      'type' => 'select',
      'length' => '30',
      'values' => 
      array (
        '你' => '你',
        '我' => '我',
      ),
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1133 => 
    array (
      'id' => '1133',
      'name' => 'radio_int',
      'description' => 'radio_int',
      'model' => '193',
      'type' => 'radio_int',
      'length' => '10',
      'values' => 
      array (
        1 => '男',
        2 => '女',
      ),
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1134 => 
    array (
      'id' => '1134',
      'name' => 'radio_varchar',
      'description' => 'radio_varchar',
      'model' => '193',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '我' => '我',
        '你' => '你',
      ),
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1135 => 
    array (
      'id' => '1135',
      'name' => 'checkbox_varchar',
      'description' => 'checkbox_varchar',
      'model' => '193',
      'type' => 'checkbox',
      'length' => '10',
      'values' => 
      array (
        '音乐' => '音乐',
        '电影' => '电影',
      ),
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1136 => 
    array (
      'id' => '1136',
      'name' => 'editor_full',
      'description' => 'editor_full',
      'model' => '193',
      'type' => 'wysiwyg',
      'length' => '1000',
      'values' => '',
      'width' => '800',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '18',
      'editable' => '1',
    ),
    1138 => 
    array (
      'id' => '1138',
      'name' => 'date_1',
      'description' => 'date_1',
      'model' => '193',
      'type' => 'datetime',
      'length' => '30',
      'values' => '',
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '50',
      'editable' => '1',
    ),
    1139 => 
    array (
      'id' => '1139',
      'name' => 'file_1',
      'description' => 'file_1',
      'model' => '193',
      'type' => 'file',
      'length' => '100',
      'values' => '',
      'width' => '200',
      'height' => '200',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '60',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1126',
    1 => '1127',
    2 => '1128',
    3 => '1129',
    4 => '1130',
    5 => '1131',
    6 => '1132',
    7 => '1133',
    8 => '1134',
    9 => '1135',
    10 => '1136',
    11 => '1138',
    12 => '1139',
  ),
  'searchable' => 
  array (
    0 => '1126',
    1 => '1127',
    2 => '1128',
    3 => '1129',
    4 => '1130',
    5 => '1131',
    6 => '1132',
    7 => '1133',
    8 => '1134',
    9 => '1135',
    10 => '1136',
    11 => '1138',
    12 => '1139',
  ),
);