<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['school_district']=array (
  'id' => '163',
  'name' => 'school_district',
  'description' => '校区列表',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    769 => 
    array (
      'id' => '769',
      'name' => 'district_id',
      'description' => '校区id(业务系统)',
      'model' => '163',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    770 => 
    array (
      'id' => '770',
      'name' => 'district_name',
      'description' => '校区名称(业务系统)',
      'model' => '163',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1015 => 
    array (
      'id' => '1015',
      'name' => 'district_rename',
      'description' => '校区名称',
      'model' => '163',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    771 => 
    array (
      'id' => '771',
      'name' => 'belong_school_id',
      'description' => '所属学校id',
      'model' => '163',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    772 => 
    array (
      'id' => '772',
      'name' => 'district_address',
      'description' => '校区地址',
      'model' => '163',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '769',
    1 => '770',
    2 => '1015',
    3 => '771',
    4 => '772',
  ),
  'searchable' => 
  array (
    0 => '769',
    1 => '770',
    2 => '1015',
    3 => '771',
    4 => '772',
  ),
);