<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['student_evaluate']=array (
  'id' => '174',
  'name' => 'student_evaluate',
  'description' => '学员评价',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    843 => 
    array (
      'id' => '843',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    844 => 
    array (
      'id' => '844',
      'name' => 'student_id',
      'description' => '学员id',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    845 => 
    array (
      'id' => '845',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    846 => 
    array (
      'id' => '846',
      'name' => 'court_score',
      'description' => '随堂得分',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    847 => 
    array (
      'id' => '847',
      'name' => 'investment',
      'description' => '上课投入',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    848 => 
    array (
      'id' => '848',
      'name' => 'confidence',
      'description' => '课堂自信',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    849 => 
    array (
      'id' => '849',
      'name' => 'discipline',
      'description' => '纪律意识',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    850 => 
    array (
      'id' => '850',
      'name' => 'communication',
      'description' => '人际交往',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    851 => 
    array (
      'id' => '851',
      'name' => 'imagination',
      'description' => '创造想象',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    870 => 
    array (
      'id' => '870',
      'name' => 'language_expression',
      'description' => '语言表达',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    881 => 
    array (
      'id' => '881',
      'name' => 'badge',
      'description' => '徽章称谓',
      'model' => '174',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    894 => 
    array (
      'id' => '894',
      'name' => 'writing_assignments',
      'description' => '作业检查',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '12',
      'editable' => '1',
    ),
    944 => 
    array (
      'id' => '944',
      'name' => 'assignments_total',
      'description' => '作业检查总分',
      'model' => '174',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '12',
      'editable' => '1',
    ),
    895 => 
    array (
      'id' => '895',
      'name' => 'dril',
      'description' => '课堂练习',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '13',
      'editable' => '1',
    ),
    945 => 
    array (
      'id' => '945',
      'name' => 'dril_total',
      'description' => '课堂练习总分',
      'model' => '174',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '13',
      'editable' => '1',
    ),
    899 => 
    array (
      'id' => '899',
      'name' => 'vocabulary_quiz',
      'description' => '词汇测试',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '14',
      'editable' => '1',
    ),
    946 => 
    array (
      'id' => '946',
      'name' => 'quiz_total',
      'description' => '词汇测试-总分',
      'model' => '174',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '14',
      'editable' => '1',
    ),
    896 => 
    array (
      'id' => '896',
      'name' => 'homework_completion',
      'description' => '作业完成度',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '15',
      'editable' => '1',
    ),
    897 => 
    array (
      'id' => '897',
      'name' => 'behavior',
      'description' => '表现行为',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '15',
      'editable' => '1',
    ),
    941 => 
    array (
      'id' => '941',
      'name' => 'word_num',
      'description' => '单词识记个数',
      'model' => '174',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    898 => 
    array (
      'id' => '898',
      'name' => 'class_participaton',
      'description' => '课堂参与',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    947 => 
    array (
      'id' => '947',
      'name' => 'vocabulary_test',
      'description' => '可选-词汇测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    948 => 
    array (
      'id' => '948',
      'name' => 'reading_test',
      'description' => '可选-阅读测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    949 => 
    array (
      'id' => '949',
      'name' => 'grammar_test',
      'description' => '可选-语法测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    950 => 
    array (
      'id' => '950',
      'name' => 'writing_test',
      'description' => '可选-写作测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    951 => 
    array (
      'id' => '951',
      'name' => 'speaking_test',
      'description' => '可选-口语测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    952 => 
    array (
      'id' => '952',
      'name' => 'listening_test',
      'description' => '可选-听力测试',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        1 => '1颗星',
        2 => '2颗星',
        3 => '3颗星',
        4 => '4颗星',
        5 => '5颗星',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    953 => 
    array (
      'id' => '953',
      'name' => 'custom_options',
      'description' => '自定义选项',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '16',
      'editable' => '1',
    ),
    883 => 
    array (
      'id' => '883',
      'name' => 'teacher_comments',
      'description' => '老师评语',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '20',
      'editable' => '1',
    ),
    1005 => 
    array (
      'id' => '1005',
      'name' => 'study_comment',
      'description' => '学习助理评价',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '20',
      'editable' => '1',
    ),
    1006 => 
    array (
      'id' => '1006',
      'name' => 'homework_feedback',
      'description' => '作业反馈',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '20',
      'editable' => '1',
    ),
    930 => 
    array (
      'id' => '930',
      'name' => 'EvaluateTime',
      'description' => '评价时间',
      'model' => '174',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '21',
      'editable' => '1',
    ),
    931 => 
    array (
      'id' => '931',
      'name' => 'send_template_status',
      'description' => '模板消息',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '未发送',
        0 => '未发送',
        1 => '已发送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '22',
      'editable' => '1',
    ),
    1002 => 
    array (
      'id' => '1002',
      'name' => 'Journeys',
      'description' => 'Journeys',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '23',
      'editable' => '1',
    ),
    1003 => 
    array (
      'id' => '1003',
      'name' => 'Writing',
      'description' => 'Writing',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '24',
      'editable' => '1',
    ),
    1004 => 
    array (
      'id' => '1004',
      'name' => 'Novels',
      'description' => 'Novels',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '25',
      'editable' => '1',
    ),
    1007 => 
    array (
      'id' => '1007',
      'name' => 'TOEFL',
      'description' => 'TOEFL',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '26',
      'editable' => '1',
    ),
    1016 => 
    array (
      'id' => '1016',
      'name' => 'is_checked',
      'description' => '是否勾选',
      'model' => '174',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '无',
        0 => '未选中',
        1 => '选中',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '27',
      'editable' => '1',
    ),
    1023 => 
    array (
      'id' => '1023',
      'name' => 'gpa',
      'description' => 'gpa',
      'model' => '174',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '550',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '27',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '843',
    1 => '844',
    2 => '845',
    3 => '846',
    4 => '847',
    5 => '848',
    6 => '849',
    7 => '850',
    8 => '851',
    9 => '870',
    10 => '881',
    11 => '941',
    12 => '883',
    13 => '930',
    14 => '931',
    15 => '1016',
    16 => '1023',
  ),
  'searchable' => 
  array (
    0 => '843',
    1 => '844',
    2 => '845',
    3 => '846',
    4 => '847',
    5 => '848',
    6 => '849',
    7 => '850',
    8 => '851',
    9 => '870',
    10 => '881',
    11 => '894',
    12 => '944',
    13 => '895',
    14 => '945',
    15 => '899',
    16 => '946',
    17 => '896',
    18 => '897',
    19 => '941',
    20 => '898',
    21 => '947',
    22 => '948',
    23 => '949',
    24 => '950',
    25 => '951',
    26 => '952',
    27 => '953',
    28 => '883',
    29 => '1005',
    30 => '1006',
    31 => '930',
    32 => '931',
    33 => '1002',
    34 => '1003',
    35 => '1004',
    36 => '1007',
    37 => '1016',
    38 => '1023',
  ),
);