<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['student']=array (
  'id' => '164',
  'name' => 'student',
  'description' => '学员信息',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '17',
  'model_sort' => '0',
  'fields' => 
  array (
    900 => 
    array (
      'id' => '900',
      'name' => 'student_code',
      'description' => '学生id【业务】',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    775 => 
    array (
      'id' => '775',
      'name' => 'student_name',
      'description' => '姓名',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    819 => 
    array (
      'id' => '819',
      'name' => 'student_name_en',
      'description' => '学生英文名',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '0',
      'order' => '1',
      'editable' => '1',
    ),
    1099 => 
    array (
      'id' => '1099',
      'name' => 'student_name_note',
      'description' => '学员名称备注',
      'model' => '164',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    776 => 
    array (
      'id' => '776',
      'name' => 'gender',
      'description' => '性别',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        0 => '男',
        1 => '女',
        2 => '未知',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    777 => 
    array (
      'id' => '777',
      'name' => 'telephone',
      'description' => '手机号',
      'model' => '164',
      'type' => 'input',
      'length' => '11',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    781 => 
    array (
      'id' => '781',
      'name' => 'school_district_id',
      'description' => '所属校区id',
      'model' => '164',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    780 => 
    array (
      'id' => '780',
      'name' => 'course_id',
      'description' => '课程id',
      'model' => '164',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    778 => 
    array (
      'id' => '778',
      'name' => 'join_class_id',
      'description' => '班级id',
      'model' => '164',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    779 => 
    array (
      'id' => '779',
      'name' => 'status',
      'description' => '状态',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '已分班',
        2 => '未分班',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    802 => 
    array (
      'id' => '802',
      'name' => 'qrcode',
      'description' => '二维码',
      'model' => '164',
      'type' => 'file',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    812 => 
    array (
      'id' => '812',
      'name' => 'notice_jurisdiction',
      'description' => '通知权限',
      'model' => '164',
      'type' => 'checkbox',
      'length' => '10',
      'values' => 
      array (
        0 => '不接收任何通知',
        1 => '学校',
        2 => '班级',
        3 => '个人',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    960 => 
    array (
      'id' => '960',
      'name' => 'del_status',
      'description' => '删除状态',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        2 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    974 => 
    array (
      'id' => '974',
      'name' => 'isset_class',
      'description' => '是否转班',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        0 => '已转班',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    1102 => 
    array (
      'id' => '1102',
      'name' => 'quit_hour',
      'description' => '已退课时',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '已退',
        2 => '正常',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    901 => 
    array (
      'id' => '901',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1103 => 
    array (
      'id' => '1103',
      'name' => 'user_select',
      'description' => '下拉框',
      'model' => '164',
      'type' => 'select',
      'length' => '10',
      'values' => 
      array (
        1 => '选项1',
        2 => '选项2',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '20',
      'editable' => '1',
    ),
    1104 => 
    array (
      'id' => '1104',
      'name' => 'user_editor',
      'description' => '编辑器',
      'model' => '164',
      'type' => 'wysiwyg_basic',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '23',
      'editable' => '1',
    ),
    1105 => 
    array (
      'id' => '1105',
      'name' => 'select_1',
      'description' => '下拉框-模型数据',
      'model' => '164',
      'type' => 'select',
      'length' => '30',
      'values' => 
      array (
        1 => '选项1',
        2 => '选项2',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '30',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '900',
    1 => '775',
    2 => '1099',
    3 => '776',
    4 => '777',
    5 => '781',
    6 => '780',
    7 => '778',
    8 => '779',
    9 => '802',
    10 => '812',
    11 => '960',
    12 => '974',
    13 => '1102',
    14 => '901',
    15 => '1103',
    16 => '1104',
    17 => '1105',
  ),
  'searchable' => 
  array (
    0 => '900',
    1 => '775',
    2 => '819',
    3 => '1099',
    4 => '776',
    5 => '777',
    6 => '781',
    7 => '780',
    8 => '778',
    9 => '779',
    10 => '802',
    11 => '812',
    12 => '960',
    13 => '974',
    14 => '1102',
    15 => '901',
    16 => '1103',
    17 => '1104',
    18 => '1105',
  ),
);