<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['student']=array (
  'id' => '164',
  'name' => 'student',
  'description' => '学员信息',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '17',
  'model_sort' => '0',
  'fields' => 
  array (
    900 => 
    array (
      'id' => '900',
      'name' => 'student_code',
      'description' => '学生id【业务】',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    775 => 
    array (
      'id' => '775',
      'name' => 'student_name',
      'description' => '姓名',
      'model' => '164',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    776 => 
    array (
      'id' => '776',
      'name' => 'gender',
      'description' => '性别',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        0 => '男',
        1 => '女',
        2 => '未知',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    779 => 
    array (
      'id' => '779',
      'name' => 'status',
      'description' => '状态',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        1 => '已分班',
        2 => '未分班',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    812 => 
    array (
      'id' => '812',
      'name' => 'notice_jurisdiction',
      'description' => '通知权限',
      'model' => '164',
      'type' => 'checkbox',
      'length' => '10',
      'values' => 
      array (
        0 => '不接收任何通知',
        1 => '学校',
        2 => '班级',
        3 => '个人',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    960 => 
    array (
      'id' => '960',
      'name' => 'del_status',
      'description' => '删除状态',
      'model' => '164',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '正常',
        1 => '正常',
        2 => '已删除',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    1103 => 
    array (
      'id' => '1103',
      'name' => 'user_select',
      'description' => '下拉框',
      'model' => '164',
      'type' => 'select',
      'length' => '10',
      'values' => 
      array (
        1 => '选项1',
        2 => '选项2',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '20',
      'editable' => '1',
    ),
    1104 => 
    array (
      'id' => '1104',
      'name' => 'user_editor',
      'description' => '编辑器',
      'model' => '164',
      'type' => 'wysiwyg',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '23',
      'editable' => '1',
    ),
    1105 => 
    array (
      'id' => '1105',
      'name' => 'select_1',
      'description' => '下拉框_int',
      'model' => '164',
      'type' => 'radio_int',
      'length' => '10',
      'values' => 
      array (
        1 => '选项1',
        2 => '选项2',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '30',
      'editable' => '1',
    ),
    1115 => 
    array (
      'id' => '1115',
      'name' => 'json_1',
      'description' => 'json_1',
      'model' => '164',
      'type' => 'textarea_json',
      'length' => '1000',
      'values' => '',
      'width' => '500',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '50',
      'editable' => '1',
    ),
    1116 => 
    array (
      'id' => '1116',
      'name' => 'json_2',
      'description' => 'json_2',
      'model' => '164',
      'type' => 'textarea_json',
      'length' => '1000',
      'values' => '',
      'width' => '500',
      'height' => '300',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '66',
      'editable' => '1',
    ),
    1117 => 
    array (
      'id' => '1117',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '164',
      'type' => 'datetime',
      'length' => '50',
      'values' => '',
      'width' => '300',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '80',
      'editable' => '1',
    ),
    1118 => 
    array (
      'id' => '1118',
      'name' => 'file_upload',
      'description' => '文件上传',
      'model' => '164',
      'type' => 'file',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '100',
      'editable' => '1',
    ),
    1124 => 
    array (
      'id' => '1124',
      'name' => 'json_3',
      'description' => 'json_3',
      'model' => '164',
      'type' => 'textarea_json',
      'length' => '',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '300',
      'editable' => '1',
    ),
    1125 => 
    array (
      'id' => '1125',
      'name' => 'text_3',
      'description' => 'text_3',
      'model' => '164',
      'type' => 'wysiwyg',
      'length' => '',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '599',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '900',
    1 => '775',
    2 => '776',
    3 => '779',
    4 => '812',
    5 => '960',
    6 => '1103',
    7 => '1104',
    8 => '1105',
    9 => '1115',
    10 => '1116',
    11 => '1117',
    12 => '1118',
    13 => '1124',
    14 => '1125',
  ),
  'searchable' => 
  array (
    0 => '900',
    1 => '775',
    2 => '776',
    3 => '779',
    4 => '812',
    5 => '960',
    6 => '1103',
    7 => '1104',
    8 => '1105',
    9 => '1115',
    10 => '1116',
    11 => '1117',
    12 => '1124',
    13 => '1125',
  ),
);