<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['timetable']=array (
  'id' => '189',
  'name' => 'timetable',
  'description' => '课表信息',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '18',
  'model_sort' => '0',
  'fields' => 
  array (
    1065 => 
    array (
      'id' => '1065',
      'name' => 'class_date',
      'description' => '上课日期',
      'model' => '189',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    1066 => 
    array (
      'id' => '1066',
      'name' => 'class_time',
      'description' => '上课时间',
      'model' => '189',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    1067 => 
    array (
      'id' => '1067',
      'name' => 'classroom_id',
      'description' => '教室编号',
      'model' => '189',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    1068 => 
    array (
      'id' => '1068',
      'name' => 'classroom_name',
      'description' => '教室名称',
      'model' => '189',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    1069 => 
    array (
      'id' => '1069',
      'name' => 'teacher_code',
      'description' => '老师编码',
      'model' => '189',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
    1070 => 
    array (
      'id' => '1070',
      'name' => 'teacher_name',
      'description' => '老师名称',
      'model' => '189',
      'type' => 'input',
      'length' => '100',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    1071 => 
    array (
      'id' => '1071',
      'name' => 'belong_class_id',
      'description' => '所属班级id',
      'model' => '189',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    1072 => 
    array (
      'id' => '1072',
      'name' => 'belong_curriculum_id',
      'description' => '所属课程id',
      'model' => '189',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1085 => 
    array (
      'id' => '1085',
      'name' => 'online_code',
      'description' => '网课id',
      'model' => '189',
      'type' => 'input',
      'length' => '30',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1087 => 
    array (
      'id' => '1087',
      'name' => 'zoom',
      'description' => 'zoom录像',
      'model' => '189',
      'type' => 'textarea',
      'length' => '255',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1073 => 
    array (
      'id' => '1073',
      'name' => 'last_update_time',
      'description' => '最后更新时间',
      'model' => '189',
      'type' => 'input',
      'length' => '50',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    1086 => 
    array (
      'id' => '1086',
      'name' => 'template_message',
      'description' => '模板消息',
      'model' => '189',
      'type' => 'radio',
      'length' => '10',
      'values' => 
      array (
        '' => '未发送',
        1 => '已发送',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1065',
    1 => '1066',
    2 => '1067',
    3 => '1068',
    4 => '1069',
    5 => '1070',
    6 => '1071',
    7 => '1072',
    8 => '1085',
    9 => '1087',
    10 => '1073',
    11 => '1086',
  ),
  'searchable' => 
  array (
    0 => '1065',
    1 => '1066',
    2 => '1067',
    3 => '1068',
    4 => '1069',
    5 => '1070',
    6 => '1071',
    7 => '1072',
    8 => '1085',
    9 => '1087',
    10 => '1073',
    11 => '1086',
  ),
);