<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['wonderful_moment']=array (
  'id' => '175',
  'name' => 'wonderful_moment',
  'description' => '学员精彩瞬间',
  'perpage' => '50',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'belong_group' => '25',
  'model_sort' => '0',
  'fields' => 
  array (
    855 => 
    array (
      'id' => '855',
      'name' => 'headmaster_id',
      'description' => '班主任id',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    857 => 
    array (
      'id' => '857',
      'name' => 'lesson_id',
      'description' => '课次id',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    971 => 
    array (
      'id' => '971',
      'name' => 'student_id',
      'description' => '学生id',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    860 => 
    array (
      'id' => '860',
      'name' => 'pictures_video_1',
      'description' => '精彩瞬间1',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '6',
      'editable' => '1',
    ),
    884 => 
    array (
      'id' => '884',
      'name' => 'text_1',
      'description' => '文案1',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    1009 => 
    array (
      'id' => '1009',
      'name' => 'rotate_1',
      'description' => '是否旋转1',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '7',
      'editable' => '1',
    ),
    885 => 
    array (
      'id' => '885',
      'name' => 'text_2',
      'description' => '文案2',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    861 => 
    array (
      'id' => '861',
      'name' => 'pictures_video_2',
      'description' => '精彩瞬间2',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    1010 => 
    array (
      'id' => '1010',
      'name' => 'rotate_2',
      'description' => '是否旋转2',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '8',
      'editable' => '1',
    ),
    886 => 
    array (
      'id' => '886',
      'name' => 'text_3',
      'description' => '文案3',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    862 => 
    array (
      'id' => '862',
      'name' => 'pictures_video_3',
      'description' => '精彩瞬间3',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    1011 => 
    array (
      'id' => '1011',
      'name' => 'rotate_3',
      'description' => '是否旋转3',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '9',
      'editable' => '1',
    ),
    863 => 
    array (
      'id' => '863',
      'name' => 'pictures_video_4',
      'description' => '精彩瞬间4',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    887 => 
    array (
      'id' => '887',
      'name' => 'text_4',
      'description' => '文案4',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    1012 => 
    array (
      'id' => '1012',
      'name' => 'rotate_4',
      'description' => '是否旋转4',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '10',
      'editable' => '1',
    ),
    864 => 
    array (
      'id' => '864',
      'name' => 'pictures_video_5',
      'description' => '精彩瞬间5',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    888 => 
    array (
      'id' => '888',
      'name' => 'text_5',
      'description' => '文案5',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    1013 => 
    array (
      'id' => '1013',
      'name' => 'rotate_5',
      'description' => '是否旋转5',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '11',
      'editable' => '1',
    ),
    1036 => 
    array (
      'id' => '1036',
      'name' => 'pictures_video_6',
      'description' => '精彩瞬间6',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1037 => 
    array (
      'id' => '1037',
      'name' => 'text_6',
      'description' => '文案6',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1038 => 
    array (
      'id' => '1038',
      'name' => 'rotate_6',
      'description' => '是否旋转6',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '12',
      'editable' => '1',
    ),
    1039 => 
    array (
      'id' => '1039',
      'name' => 'pictures_video_7',
      'description' => '精彩瞬间7',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1040 => 
    array (
      'id' => '1040',
      'name' => 'text_7',
      'description' => '文案7',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1041 => 
    array (
      'id' => '1041',
      'name' => 'rotate_7',
      'description' => '是否旋转7',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '13',
      'editable' => '1',
    ),
    1042 => 
    array (
      'id' => '1042',
      'name' => 'pictures_video_8',
      'description' => '精彩瞬间8',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    1043 => 
    array (
      'id' => '1043',
      'name' => 'text_8',
      'description' => '文案8',
      'model' => '175',
      'type' => 'textarea',
      'length' => '1000',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    1044 => 
    array (
      'id' => '1044',
      'name' => 'rotate_8',
      'description' => '是否旋转8',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '14',
      'editable' => '1',
    ),
    1045 => 
    array (
      'id' => '1045',
      'name' => 'pictures_video_9',
      'description' => '精彩瞬间9',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1046 => 
    array (
      'id' => '1046',
      'name' => 'text_9',
      'description' => '文案9',
      'model' => '175',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1047 => 
    array (
      'id' => '1047',
      'name' => 'rotate_9',
      'description' => '是否旋转9',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '15',
      'editable' => '1',
    ),
    1048 => 
    array (
      'id' => '1048',
      'name' => 'pictures_video_10',
      'description' => '精彩瞬间10',
      'model' => '175',
      'type' => 'file',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1049 => 
    array (
      'id' => '1049',
      'name' => 'text_10',
      'description' => '文案10',
      'model' => '175',
      'type' => 'textarea',
      'length' => '500',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
    1050 => 
    array (
      'id' => '1050',
      'name' => 'rotate_10',
      'description' => '是否旋转10',
      'model' => '175',
      'type' => 'input',
      'length' => '10',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '16',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '855',
    1 => '857',
    2 => '971',
    3 => '860',
    4 => '884',
    5 => '1009',
    6 => '885',
    7 => '861',
    8 => '1010',
    9 => '886',
    10 => '862',
    11 => '1011',
    12 => '863',
    13 => '887',
    14 => '1012',
    15 => '864',
    16 => '888',
    17 => '1013',
    18 => '1036',
    19 => '1037',
    20 => '1038',
    21 => '1039',
    22 => '1040',
    23 => '1041',
    24 => '1042',
    25 => '1043',
    26 => '1044',
    27 => '1045',
    28 => '1046',
    29 => '1047',
    30 => '1048',
    31 => '1049',
    32 => '1050',
  ),
  'searchable' => 
  array (
    0 => '855',
    1 => '857',
    2 => '971',
    3 => '860',
    4 => '884',
    5 => '1009',
    6 => '885',
    7 => '861',
    8 => '1010',
    9 => '886',
    10 => '862',
    11 => '1011',
    12 => '863',
    13 => '887',
    14 => '1012',
    15 => '864',
    16 => '888',
    17 => '1013',
    18 => '1036',
    19 => '1037',
    20 => '1038',
    21 => '1039',
    22 => '1040',
    23 => '1041',
    24 => '1042',
    25 => '1043',
    26 => '1044',
    27 => '1045',
    28 => '1046',
    29 => '1047',
    30 => '1048',
    31 => '1049',
    32 => '1050',
  ),
);