<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting=array (
  'site_name' => '正式-家校后台系统',
  'site_domain' => 'https://eick12nm.xyz',
  'site_logo' => 'images/logo_kp.png',
  'site_icp' => '',
  'site_terms' => '',
  'site_stats' => '',
  'site_footer' => '',
  'site_status' => '1',
  'site_close_reason' => '网站维护升级中......',
  'site_keyword' => '正式-家校后台系统',
  'site_description' => '正式-家校后台系统',
  'site_theme' => 'default',
  'attachment_url' => '/ocean/attachments',
  'attachment_dir' => 'attachments',
  'attachment_type' => '*.jpg;*.gif;*.png;*.doc',
  'attachment_maxupload' => '2097152',
  'thumbs_preferences' => '[]',
);